spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nayaknayak12390@gmail.com
    password: tyqj tcwa lqca ibxx
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
